### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by DanGiaime**

### CODE REVIEW

**Comment by georgemorgan** [comment]
I think this is too little information for the top level README. I am pretty comfortable with the length and verbosity of what we've got.

**Comment by georgemorgan** [comment]
@DanGiaime Are you going to add to this?

**Comment by georgemorgan** [comment]
@DanGiaime I am going to close this if this is stale

**Comment by DanGiaime** [comment]
Had my notifications set up wrong :(
Will update within the next two days.

**Pull request closed without merging**
